version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5433:5432
    expose:
      - 5432
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py initial &&
             python manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env 